apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default
  source:
    # Sync Root Application first
    repoURL: https://github.com/smooti/platform-bootstrap.git
    path: apps/argo-root
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    # Sync projects
    - repoURL: https://github.com/smooti/platform-bootstrap.git
      targetRevision: HEAD
      path: projects

    # Sync core apps
    - repoURL: https://github.com/smooti/platform-bootstrap.git
      targetRevision: HEAD
      path: apps/core